server:
  port: 18869

client:
  port: 18869
  node: dgx001
 #file_path: /om2/user/kirjner/WormWork/targettrack/unlabeled_worm_head_example.h5
  file_path: /om2/user/kirjner/WormWork/targettrack/20250115-test-5-dog-less-sparsified-median-flipped-frames.h5
